%clear all
%close all
%%
function compara_isi_ic(dirName, filePattern, startRow, xCol, yCol, groupISIThresh, isiFSCSThresh, isiBSThresh, outFileName, saveMode, outputDir)%, faceAlpha, plotInd)
%     dirName = 'data\log';
%     filePattern = '*d.001*.dat';
%     startRow = 17;
%     xCol = 2;
%     yCol = 1;
%     groupISIThresh = 10;
%     isiFSCSThresh = 20;
%     isiBSThresh = 80;
%     faceAlpha = 0.5;
%     plotInd = [3,4];
    if (nargin < 11) || isempty(outputDir)
        outputDir = fullfile(dirName,'..');
    end

    files = dir(fullfile(dirName, filePattern ));

    % cMapFunc = { @(x)1-gray(x),...
    %              @jet,...
    %              @(x)1-hot(x),...
    %              @cool,...
    %              @(x)1-spring(x),...
    %              @(x)1-summer(x),...
    %              @(x)1-autumn(x),...
    %              @(x)1-winter(x),...
    %              @(x)1-bone(x),...
    %              @(x)1-copper(x),...
    %              @(x)1-pink(x),...
    %              @lines };
    % 
    % getCMap = @(ind) cMapFunc{mod(ind-1,length(cMapFunc))+1};

    nFiles = length(files);

    isiPlot = repmat(struct('fileName', [],...
                            'isiAvg', [],...
                            'x', [],...
                            'y', [],...
                            'z', [],...
                            'c', [],...
                            'alpha', [],...
                            'cLabels', []), 1, nFiles);

    %% calculating
    for i = 1:nFiles
        isiPlot(i).fileName = fullfile(dirName,files(i).name);

        disp([ '* importing data: ', files(i).name ]);

        [ isiData, dataLabels ] = import_isiData(isiPlot(i).fileName, startRow);

        disp('* averaging ISI...');

        [ isiPlot(i).isiAvg, yVal, xVal ] = averageISI(isiData, dataLabels, xCol, yCol, groupISIThresh);

        disp('* generating plot...');

        [ isiPlot(i).x,isiPlot(i).y,isiPlot(i).z,isiPlot(i).c,isiPlot(i).alpha,isiPlot(i).cLabels ] = ...
            getISIMeshPlot(isiPlot(i).isiAvg, dataLabels{xCol}, dataLabels{yCol}, 'ISIAvg', isiFSCSThresh, isiBSThresh);
        
        isiplotFileName = regexprep(files(i).name, '^isi', 'isiPlot', 'ignorecase');
        isiplotFileName = fullfile(outputDir, isiplotFileName);
        if (strcmp(saveMode,'text'))
            disp(['* saving isiPlot into text file: ', isiplotFileName]);
            dlmwrite(isiplotFileName, ...
                [ '# isiPlot file -- data generated by getISIMeshPlot function' ], 'newline', 'unix', 'delimiter', '');
            dlmwrite(isiplotFileName, ...
                [ '# col_mat_size = ', strjoin(cellstr(num2str(size(isiPlot(i).x)','%d'))',',') ], '-append', 'newline', 'unix', 'delimiter', '');
            dlmwrite(isiplotFileName, ...
                [ '# cLabels = ', strjoin(isiPlot(i).cLabels,',') ], '-append', 'newline', 'unix', 'delimiter', '');
            dlmwrite(isiplotFileName, ...
                [ '# plot_labels = x->T,y->x_R,z->ISIAvg,c->colorInd,alpha->alpha' ], '-append', 'newline', 'unix', 'delimiter', '');
            dlmwrite(isiplotFileName, ...
                [ '# x    y    z    c    alpha' ], '-append', 'newline', 'unix', 'delimiter', '');
            dlmwrite(isiplotFileName,...
                [ isiPlot(i).x(:), isiPlot(i).y(:), isiPlot(i).z(:), isiPlot(i).c(:), isiPlot(i).alpha(:) ], ...
                    '-append', ...
                    'precision', '%17.8E', ...
                    'delimiter', '\t', ...
                    'newline', 'unix');
        else
            p = rmfield(isiPlot(i),'isiAvg');
            p.xLabel = dataLabels{2};
            p.yLabel = dataLabels{1};
            p.zLabel = [dataLabels{3}, 'Avg'];
            p.cLabel = 'colorInd';
            p.alphaLabel = 'alpha';
            p = orderfields(p,{'fileName', 'cLabels', 'xLabel', 'yLabel', 'zLabel', 'cLabel', 'alphaLabel', 'x', 'y', 'z', 'c', 'alpha'});
            isiplotFileName = regexprep(isiplotFileName,'\.dat$','.mat','ignorecase');
            disp(['* saving isiPlot into MAT file: ', isiplotFileName]);
            save(isiplotFileName, 'p', '-v7.3')
        end
    end
end